// Когда мы типизируем экшены, мы говорим интерпретатору TypeScript,
// что у нас есть только такие экшены и никаких больше.Так мы защищаем
// код от опечаток и вызова несуществующих или некорректных экшенов.
// Для начала добавим TypeScript к типам экшенов:


export const CONSTRUCTOR_SET: 'CONSTRUCTOR_SET' = 'CONSTRUCTOR_SET';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR_RESET'  = 'CONSTRUCTOR_RESET';
export const CONSTRUCTOR_DELETE: 'CONSTRUCTOR_DELETE'  = 'CONSTRUCTOR_DELETE';
export const CONSTRUCTOR_REORDER: 'CONSTRUCTOR_REORDER'  = 'CONSTRUCTOR_REORDER';

export const SET_INGREDIENT_MODAL: 'SET_INGREDIENT_MODAL' = 'SET_INGREDIENT_MODAL';
export const RESET_INGREDIENT_MODAL: 'RESET_INGREDIENT_MODAL' = 'RESET_INGREDIENT_MODAL';

export const GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST' = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED: 'GET_ITEMS_FAILED' = 'GET_ITEMS_FAILED';

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED';
export const RESET_ORDER: 'RESET_ORDER' = 'RESET_ORDER';

export const AUTH_CHECKED: "AUTH_CHECKED" = "AUTH_CHECKED";

export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";

export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST" = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS" = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED: "LOGIN_USER_FAILED" = "LOGIN_USER_FAILED";

export const LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST" = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS" = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED: "LOGOUT_USER_FAILED" = "LOGOUT_USER_FAILED";

export const ADD_USER_REQUEST: "ADD_USER_REQUEST" = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS: "ADD_USER_SUCCESS" = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED: "ADD_USER_FAILED" = "ADD_USER_FAILED";

export const UPD_PASSWORD_REQUEST: "UPD_PASSWORD_REQUEST" = "UPD_PASSWORD_REQUEST";
export const UPD_PASSWORD_SUCCESS: "UPD_PASSWORD_SUCCESS" = "UPD_PASSWORD_SUCCESS";
export const UPD_PASSWORD_FAILED: "UPD_PASSWORD_FAILED" = "UPD_PASSWORD_FAILED";

export const RST_PASSWORD_REQUEST: "RST_PASSWORD_REQUEST" = "RST_PASSWORD_REQUEST";
export const RST_PASSWORD_SUCCESS: "RST_PASSWORD_SUCCESS" = "RST_PASSWORD_SUCCESS";
export const RST_PASSWORD_FAILED: "RST_PASSWORD_FAILED" = "RST_PASSWORD_FAILED";

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_CONNECTION_WITH_TOKEN: 'WS_CONECTION_WITH_TOKEN' = 'WS_CONECTION_WITH_TOKEN';